---
title: "Dog Adoption Survey Results"
author: "John Calzaretta, Aditya Mengani, Jesus Fernandex"
date: "12/06/2022"
output:
  pdf_document: default
  word_document: default
---

```{r install packages, message = FALSE}
install.packages("lmtest")
install.packages("sandwich")
install.packages("AER")
install.packages("patchwork")
install.packages("stargazer")
```

```{r load packages, message = FALSE}
library(stargazer)
library(data.table)
library(sandwich)
library(lmtest)
library(AER) 
library(ggplot2) 
library(patchwork)
library(dplyr)
```

```{r}
robust_se <- function(mod, type = 'HC3') { 
  sqrt(diag(vcovHC(mod, type)))
}
```


```{r load  data}
d <- fread('../data/das_results_cleaned.csv')
head(d)
```

# PHASE 1 MODELS: Treatment + Covariates (No Fixed Effects)
```{r create treatment interation groupings}
d$trtmnt_interaction <- ifelse(
  (d$msg_treat_ind==1)&(d$shelter_tp==0), 4, ifelse(
    (d$msg_treat_ind==1)&(d$shelter_tp==1), 5, ifelse(
      (d$msg_treat_ind==1)&(d$shelter_tp==2), 6, ifelse(
        (d$msg_treat_ind==0)&(d$shelter_tp==0),  0, ifelse(
          (d$msg_treat_ind==0)&(d$shelter_tp==1), 1, 2)))))
```

```{r treatment interaction model, include=TRUE} 
model_inter <- d[ , lm(rating ~ factor(trtmnt_interaction))]

model_inter_some_covs <- d[ , lm(rating ~ factor(trtmnt_interaction) +
                              factor(age_bin) + 
                              factor(gender) + 
                              factor(marital) + 
                              factor(income_bin) +
                              factor(own_dog) + 
                              factor(dog_or_cat) + 
                              factor(adopt_or_shop) + 
                              factor(dog_size) 
                              )]

model_inter_all_covs<- d[ , lm(rating ~ factor(trtmnt_interaction) +
                              factor(age_bin) + 
                              factor(gender) + 
                              factor(marital) + 
                              factor(income_bin) + 
                              factor(own_dog) + 
                              factor(dog_or_cat) + 
                              factor(adopt_or_shop) + 
                              factor(dog_size) + 
                              factor(state) +
                              duration
                              )]

stargazer(
  model_inter,
  model_inter_some_covs,
  model_inter_all_covs,
  type = 'text', 
  se = list(
    robust_se(model_inter),
    robust_se(model_inter_some_covs), 
    robust_se(model_inter_all_covs)
  ), omit.stat = c('ser', 'F')
)

```

# PHASE 2: Add Fixed Effects
```{r treatment interaction plus covariates model, include=TRUE} 
model_inter_all_covs_fixed <- d[ , lm(rating ~ factor(trtmnt_interaction) +
                              factor(age_bin) + 
                              factor(gender) + 
                              factor(marital) + 
                              factor(income_bin) + 
                              factor(own_dog) + 
                              factor(dog_or_cat) + 
                              factor(adopt_or_shop) + 
                              factor(dog_size) + 
                              factor(state) + 
                              duration +
                              factor(ip)
                              )]

model_inter_fixed <- d[ , lm(rating ~ factor(trtmnt_interaction) + factor(ip))]

d_ao <- d %>%
  group_by(ip) %>%
  summarize(outcome_avg = mean(rating))
d2 <- inner_join(d, d_ao, by="ip")

model_avg_outcomes <- d2[ , lm(rating ~ factor(trtmnt_interaction) +
                              factor(age_bin) + 
                              factor(gender) + 
                              factor(marital) + 
                              factor(income_bin) + 
                              factor(own_dog) + 
                              factor(dog_or_cat) + 
                              factor(adopt_or_shop) + 
                              factor(dog_size) + 
                              factor(state) +
                              outcome_avg
                              )]

stargazer(
  model_inter_all_covs,
  model_inter_all_covs_fixed,
  model_inter_fixed,
  model_avg_outcomes,
  type = 'text', 
  se = list(
    robust_se(model_inter_all_covs),
    robust_se(model_inter_all_covs_fixed), 
    robust_se(model_inter_fixed),
    robust_se(model_avg_outcomes)
  ), 
  omit.stat = c('ser', 'F')
)

```

## Phase 3: COVARIATE BALANCE TEST
```{r}
model_benchmark <- d[ , lm(msg_treat_ind ~ 1)]
model_cov <- d[ , lm(msg_treat_ind ~ factor(income_bin))]

res <- coeftest(model_cov, vcovHC)
print(res)

print(anova(model_benchmark, model_cov))
```





## SAVE FOR FORMATTING
```{r}

stargazer(
  model_inter,
  model_inter_some_covs,
  model_inter_all_covs,
  type = 'text', 
  se = list(
    robust_se(model_inter), 
    robust_se(model_inter_some_covs), 
    robust_se(model_inter_all_covs)
  ), 
  omit.stat = c('ser', 'F'),
  title="Regression Results", 
  align=TRUE,
  dep.var.labels="Rating",
  covariate.labels=c("No Message + Traditional Shelter Type",
                     "No Message + No-Kill Shelter Type",
                     "Message + No Shelter Info",
                     "Message + Traditional Shelter Type",
                     "Message + No-Kill Shelter Type",
                     "Age 18-24",
                     "Age 25-34",
                     "Age 35-44",
                     "Age 45-54",
                     "Age 55-64",
                     "Age 65+", 
                     "Male",
                     "Transgender",
                     "Other Gender",
                     "In Relationship",
                     "Single",
                     "Income 25k-50k",
                     "Income 50k-75k",
                     "Income 75k-100k",
                     "Income 100k-150k",
                     "Income 150k+",
                     "Own Pet, Non-Dog",
                     "Own Dog",
                     "Prefers Dogs",
                     "No Pet Preference",
                     "Prefers Shopping for Dogs",
                     "Prefers Medium Dogs",
                     "Prefers Large Dogs"
                     )
)
```

